# Generated by Django 5.0.2 on 2024-04-27 21:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 4, 27, 16, 31, 24, 48068))),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 4, 27, 16, 31, 24, 48068))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('contraseña', models.CharField(max_length=250)),
                ('celular', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 4, 27, 16, 31, 24, 48068))),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 4, 27, 16, 31, 24, 48068))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nombre_producto', models.CharField(blank=True, max_length=100)),
                ('abreviatura', models.CharField(blank=True, max_length=10)),
                ('descripcion', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tipo_transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 4, 27, 16, 31, 24, 48068))),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 4, 27, 16, 31, 24, 48068))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('abreviatura', models.CharField(blank=True, max_length=10)),
                ('descripcion', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClienteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 4, 27, 16, 31, 24, 48068))),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 4, 27, 16, 31, 24, 48068))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('numero_cuenta', models.CharField(max_length=50)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.cliente')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.producto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 4, 27, 16, 31, 24, 48068))),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 4, 27, 16, 31, 24, 48068))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('monto', models.IntegerField()),
                ('Tipo_transaccion', models.CharField(blank=True, default=True, null=True)),
                ('id_cliente_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.clienteproducto')),
                ('id_tipo_transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.tipo_transaccion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
