# Generated by Django 5.0.2 on 2024-04-27 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_cliente_celular_alter_cliente_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 16, 53, 0, 53748)),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 16, 53, 0, 53748)),
        ),
        migrations.AlterField(
            model_name='clienteproducto',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 16, 53, 0, 53748)),
        ),
        migrations.AlterField(
            model_name='clienteproducto',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 16, 53, 0, 53748)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 16, 53, 0, 53748)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 16, 53, 0, 53748)),
        ),
        migrations.AlterField(
            model_name='tipo_transaccion',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 16, 53, 0, 53748)),
        ),
        migrations.AlterField(
            model_name='tipo_transaccion',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 16, 53, 0, 53748)),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 16, 53, 0, 53748)),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 16, 53, 0, 53748)),
        ),
    ]
